### PR TITLE
[ADD]hr_expense_advance_clearing: added module for issue: 628

### PR DESCRIPTION
**Pull request by mra-odoo**
Hi Kitti,

Ref: /issues/628

Please check.

Pending points todo:
- Clearning supplier invoice first line should be non editable.
- You may have to comment code: https://github.com/pabi2/pb2_generic/blob/master/hr_expense_auto_invoice/models/account_invoice.py#L34 to test this module since this commit does not allow us to validate clearing invoice.
- And travis error from other module which does not allow PR to green. https://travis-ci.org/pabi2/pb2_generic/jobs/136394112

Thanks,
Mustufa

### CODE REVIEW

**Comment by pabi2** [comment]
Hi Mustu, some issue from the review.

1) I found that for the first line to be non editable, you used fields_view_get(), and it make all the hidden chartfields appear (you have to install pabi_chartfield first). I test removing fields_view_get and it seem ok (yet it will be editable).

image

2) For Employee Clearing, can we by pass the exception about expense amount != invoice amount. As we know, the invoice amount count be - 10,000 + 10,000 = 0.0

3) For Travis, we will check later.

**Comment by pabi2** [comment]
Additional,

* Found that, the Clearing Expense document is also shown in Expense menu.

**Comment by mra-odoo** [comment]
Hi Kitti,

Above points are done, can you please check? 

Thanks,

**Comment by pabi2** [comment]
Hi Mustu
I have some fix, so please pull from the latest.
Here are review,

1) The clearing's first negative advance line. Amount should not exceed the uncleared amount.
I.e., given advance 1,000
- 1st clearing at 600, the first negative line is 600 and the expense line is 600 -> Net = 0.0 (it should auto reconcile/paid)

Once invoice is confirmed, the uncleared balance is 400

- 2nd clearing at, however is 700 (over use), the first negative line should be 400 (now it is 700) and the expense line should be 700, net = +300 (left to pay to employee)

2) For the clearing, as Invoice validated, I still not see it is reconciled (still not paid, and still see it in payment)
- Case Net = 0.0, it should be reconciled/paid immediately.
- Case Net > 0, only net amount left to be paid.

**Comment by pabi2** [comment]
Hello Mustu I think I find the exact manual window (but we need it auto).
Says, we have clearing -> supplier invoice with -500 and + 700 with Net = 200.
Now, we want to clear the 500, and left 200 to pay more to employee. I can do it manually in Journal Item window.

image
image

Then, if you go to Supplier Payment, you will see only 1 line to pay @ 200

**Comment by mra-odoo** [comment]
Hi Kitti,

Above changes done for partial reconcile (ie net total > 0.0) but we are having issue if we try to reconcile clearing invoice with net=0.0 then it gives error "Entries are on same account or already reconciled." so we skipped that on validation of invoice, can you please try to make full clear invoice reconcilation using "Reconcile Entry" wizard and see ?

Can you please give some hint.

Thanks,

**Comment by pabi2** [comment]
Hi Mustu,

I created advance with 1 product line "Advance" = 1000 and clearing with 1 production line "Service" = 1000.

Then, confirm Invoice, it is not paid (OK, as you mentioned). So, I go to reconcile entries, and match the 1000 and 1000. it can reconcile without problem. I came back to Invoice and see it as Paid.

Or, is it matter to use product "Service" with different account code than "Advance"?

**Pull request merged**
