### PR TITLE
Add account voucher deduction module

### PR DESCRIPTION
**Pull request by mra-odoo**
1.     Upgrade to V8 API
2.     Coding standard
3.     Unit Test (unittest2 only)

Ref: /issues/165

Thanks,

### CODE REVIEW

**Comment by mra-odoo** [comment]
Hi Kitti,

Travis failure due to dependency issue of hook module. Other things seems ok. 

Thanks,

**Comment by mra-odoo** [comment]
We have to wait till https://github.com/pabi2/pb2_base_technical/pull/3 PR

**Comment by pabi2** [comment]
Hi Mustu.
I look at my hr_expense_auto_invoice. But it was ok on its own. But it error on the line related to account_voucher, which may be from 
`
openerp_test openerp.addons.account_voucher_deduction.tests.test_account_voucher_deduction: ` ValueError: "multiple_reconcile_ded_amount_hook() takes exactly 8 arguments (6 given)" while evaluating
`

Possible?

**Comment by mra-odoo** [comment]
Fixed travis

**Pull request merged**
