### PR TITLE
Enh hr expense auto invoice (NOT IN USE)

### PR DESCRIPTION
**Pull request by mra-odoo**
Hi Kitti,

This PR to fix below issues.

1. /issues/591
2. /issues/601
3. /issues/602

Thanks,

### CODE REVIEW

**Comment by mra-odoo** [comment]
Fixed Travis

**Comment by mra-odoo** [comment]
Fixed Travis

**Comment by pabi2** [comment]
This one is pending for merge. Still discuss with Lek whether we better off improve tax table instead of VAT Info

**Comment by pabi2** [comment]
Hi, please ignore this branch for now. We are considering using Tax Table instead.

Sorry!

**Pull request closed without merging**
