### PR TITLE
Add account move line doc ref

### PR DESCRIPTION
**Pull request by mra-odoo**
Hi Kitti,

This addon, will add new "doc_ref" field in account.move.line, and filled when,

    Invoices (customer/supplier and including refunds, etc.)
    Payment (customer/supplier)
    Expense (don't need anymore as we use hr_expense_auto_invoice)
    etc., anything else as you see when coding.

Thanks,

### CODE REVIEW

**Comment by mra-odoo** [comment]
Fixed travis error.

**Comment by mra-odoo** [comment]
Fixed travis error.

**Comment by mra-odoo** [comment]
This branch will be green once https://github.com/pabi2/pb2_base_technical/pull/8 merge

**Comment by pabi2** [comment]
Hell Mustu, I still don't see the code for Account Voucher.

**Pull request merged**
